name: PR - Build / Test

on:
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src/my-web-app

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: ./src/my-web-app

      - name: Publish
        run: dotnet publish -c Release -o ./publish
        working-directory: ./src/my-web-app

      - name: Create zip file
        run: zip -r myapp.zip ./publish
        working-directory: ./src/my-web-app

      - name: Upload zip file
        uses: actions/upload-artifact@v4
        with:
          name: myapp
          path: ./src/my-web-app/myapp.zip
