name: Push Default and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4.1.0
        with:
          dotnet-version: "8.0.x"

      - name: Restore dependencies
        run: dotnet restore
        working-directory: ./src/my-web-app

      - name: Build
        run: dotnet build --no-restore --configuration Release
        working-directory: ./src/my-web-app

      - name: Publish
        run: dotnet publish -c Release -o ./publish
        working-directory: ./src/my-web-app

      - name: Create zip file
        run: zip -r myapp.zip ./publish
        working-directory: ./src/my-web-app

      - name: Upload zip file
        uses: actions/upload-artifact@v4
        with:
          name: myapp
          path: ./src/my-web-app/myapp.zip

  deploy-to-dev:
    runs-on: ubuntu-latest
    needs: build-and-test

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: myapp
          path: ./src/my-web-app

      - name: Login to Azure
        uses: azure/login@v2.2.0
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ secrets.WEB_APP_NAME }}
          slot-name: dev
          package: ./src/my-web-app/myapp.zip
